name: github pages

on:
    push:
        branches:
        - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        - uses: actions/checkout@v2

        - name: Setup Node
            uses: actions/setup-node@v4.0.1
            with:
            node-version: '20.x'

        # - name: Get yarn cache
        #     id: yarn-cache
        #     run: echo "::set-output name=dir::$(yarn cache dir)"

        # - name: Cache dependencies
        #     uses: actions/cache@v2
        #     with:
        #     path: ${{ steps.yarn-cache.outputs.dir }}
        #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        #     restore-keys: |
        #         ${{ runner.os }}-yarn-
        - run: npm install
        - run: npm build
            env:
            REACT_APP_GIT_SHA: ${{ github.SHA }}

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
            with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
